version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/app/src
    command: uvicorn src.api:app --host 0.0.0.0 --port 8001 --reload